apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: mvp-booking-service
  description:  |
    mvp-booking-service api component to display openapi specifications
spec:
  type: openapi
  owner: Deepak Baluswamy
  lifecycle: production
  definition:
    $text: https://github.com/baludeepak7/Demo/blob/main/openapi.yaml

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mvp-booking-service
  description: |
    mvp-booking-store gitlab component to display ci/cd pipelines along with merge requests
  annotations:
    gitlab.com/project-id: '48576071'
    sonarqube.org/project-key: tmf-customer-management
spec:
  type: service
  lifecycle: production
  owner: Deepak Baluswamy
  providesApis:
    - mvp-booking-service
