apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: mvp-banking-service
  description:  |
    mvp-banking-service api component to display openapi specifications
spec:
  type: openapi
  owner: Deepak Baluswamy
  lifecycle: production
  definition:
    $text: https://github.com/baludeepak7/Demo/blob/main/openapi.yaml

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mvp-banking-service
  description: |
    mvp-banking-service gitlab component to display ci/cd pipelines along with merge requests
  annotations:
    gitlab.com/project-id: '48576071'
    sonarqube.org/project-key: tmf-customer-management
    kafka.apache.org/consumer-groups: confluent/test-consumer-group
spec:
  type: service
  lifecycle: production
  owner: Deepak B
  system: TMF
  providesApis:
    - mvp-banking-service
