apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: tmf-account-management
  description:  |
    API for managing account
spec:
  type: openapi
  owner: Hemanth R
  lifecycle: production
  system: TMF
  definition:
    $text: https://github.com/baludeepak7/Demo/blob/main/tmf-account-management.yaml
    
---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tmf-account-management
  description: |
    API for managing account
  annotations:
    gitlab.com/project-id: '48576071'
    sonarqube.org/project-key: tmf-customer-management
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: Hemanth R
  system: TMF
  providesApis:
    - tmf-account-management
