apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pet-store
  description: My pet-store API
  owner: myteam
  tags:
    - api
spec:
  type: openapi
  lifecycle: production
  owner: myteam
  providesApis:
    - id: pet-store
      specPath: openapi.yaml
      lifecycle: production
