apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: pet
  description: The pet API
  tags:
    - store
    - rest
spec:
  type: openapi
  lifecycle: experimental
  owner: team-c
  path: openapi.yaml
